export const defaultRecipes = [
  {
    nombre: 'Ensalada de pollo',
    descripcion: 'Ensalada fresca con pollo desmenuzado y vegetales crujientes.',
    instrucciones: 'Mezcla el pollo cocido con lechuga, tomate y cebolla. Adereza con aceite y limón.',
    ingredientes: ['pollo', 'lechuga', 'tomate', 'cebolla', 'aceite', 'limon'],
    tiempo: 25,
    saludable: true,
    economico: true,
  },
  {
    nombre: 'Arroz con verduras',
    descripcion: 'Arroz salteado con vegetales mixtos y especias suaves.',
    instrucciones: 'Sofríe las verduras, añade arroz cocido y saltea con especias al gusto.',
    ingredientes: ['arroz', 'zanahoria', 'pimiento', 'cebolla', 'aceite', 'ajo'],
    tiempo: 30,
    saludable: true,
    economico: true,
  },
  {
    nombre: 'Pasta al pesto',
    descripcion: 'Pasta con salsa de pesto casera y queso.',
    instrucciones: 'Cocina la pasta. Licúa albahaca, ajo, aceite y queso. Mezcla todo caliente.',
    ingredientes: ['pasta', 'albahaca', 'ajo', 'aceite', 'queso'],
    tiempo: 20,
    saludable: false,
    economico: true,
  },
  {
    nombre: 'Tacos de res',
    descripcion: 'Tacos rápidos con carne de res sazonada y vegetales.',
    instrucciones: 'Saltea la carne con especias, sirve en tortillas con cebolla y tomate.',
    ingredientes: ['carne de res', 'tortillas', 'cebolla', 'tomate', 'ajo'],
    tiempo: 20,
    saludable: false,
    economico: false,
  },
  {
    nombre: 'Omelette de vegetales',
    descripcion: 'Huevos con vegetales, ideal para desayuno o cena ligera.',
    instrucciones: 'Bate huevos, agrega vegetales picados y cocina a fuego medio.',
    ingredientes: ['huevo', 'pimiento', 'espinaca', 'cebolla', 'aceite'],
    tiempo: 15,
    saludable: true,
    economico: true,
  },
  {
    nombre: 'Sopa de tomate',
    descripcion: 'Sopa cremosa de tomate con un toque de ajo y hierbas.',
    instrucciones: 'Sofríe ajo y cebolla, añade tomate y caldo, cocina y licúa.',
    ingredientes: ['tomate', 'ajo', 'cebolla', 'caldo', 'aceite'],
    tiempo: 30,
    saludable: true,
    economico: true,
  },
];
